//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTap2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
       
        public SanPham()
        {
            this.SPtheoMaus = new HashSet<SPtheoMau>();
        }
        [Display(Name = "Mã sản phẩm")]
        //
        public string MaSanPham { get; set; }
        [Display(Name = "tên sản phẩm")]
        public string TenSanPham { get; set; }
        [Display(Name = "Mã phân loại")]
        public string MaPhanLoai { get; set; }
        [Display(Name = "giá nhập")]

        [RegularExpression(@"^\d+$", ErrorMessage = "Đơn giá chỉ được nhập số.")]
        public Nullable<long> GiaNhap { get; set; }
        [Display(Name = "đơn giá nhỏ nhất")]
        [RegularExpression(@"^\d+$", ErrorMessage = "Đơn giá chỉ được nhập số.")]
        public Nullable<long> DonGiaBanNhoNhat { get; set; }
        [Display(Name = "đơn giá lớn nhất")]
        [RegularExpression(@"^\d+$", ErrorMessage = "Đơn giá chỉ được nhập số.")]
        public Nullable<long> DonGiaBanLonNhat { get; set; }
        [Display(Name = "trạng thái")]
        public Nullable<bool> TrangThai { get; set; }
        [Display(Name = "mô tả ")]
        public string MoTaNgan { get; set; }
        [Display(Name = "ảnh")]
        [FileExtensions(Extensions = "jpg", ErrorMessage = "File ảnh phải có phần mở rộng .jpg.")]
        public string AnhDaiDien { get; set; }
        [Display(Name = "nổi bật")]
        public Nullable<bool> NoiBat { get; set; }
        [Display(Name = "mã phân loại thu")]
        public string MaPhanLoaiPhu { get; set; }
        
        public virtual PhanLoai PhanLoai { get; set; }
      
        public virtual PhanLoaiPhu PhanLoaiPhu { get; set; }
       
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPtheoMau> SPtheoMaus { get; set; }
    }
}
